"""
Build a single-file portable exe using PyInstaller.
Run 'python build.py freeze' first to generate target/fmanYS/.

Plugins bundled from:
  - target/fmanYS/Plugins          (shipped)
  - %APPDATA%/fman/Plugins/Third-party  (user-installed)
  - %APPDATA%/fman/Plugins/User         (user settings/personal)
"""
import os
import shutil
import sys
from pathlib import Path

project_root = Path(__file__).parent.resolve()
target_fmanys = project_root / 'target' / 'fmanYS'
pyinstaller_dir = project_root / 'target' / 'PyInstaller'

# fbs_pyinstaller_hook.py is generated by 'python build.py freeze'
fbs_hook = pyinstaller_dir / 'fbs_pyinstaller_hook.py'
portable_hook = project_root / 'src' / 'build' / 'portable_hook.py'

import fbs
from pathlib import Path as _Path
fbs_hooks_dir = _Path(fbs.__file__).parent / 'freeze' / 'hooks'

sep = ';'  # Windows path separator for --add-data

# ---------------------------------------------------------------------------
# Copy user-installed plugins into the freeze target so PyInstaller bundles
# them. __pycache__ dirs are excluded — plugins will recompile on first run.
# ---------------------------------------------------------------------------
appdata = Path(os.environ.get('APPDATA', ''))
user_plugins_root = appdata / 'fman' / 'Plugins'

for subdir in ('Third-party', 'User'):
    src = user_plugins_root / subdir
    dst = target_fmanys / 'Plugins' / subdir
    if not src.exists():
        continue
    print(f"Copying {src} -> {dst}")
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(
        src, dst,
        ignore=shutil.ignore_patterns('__pycache__', '*.pyc', '*.pyo'),
    )

import PyInstaller.__main__

args = [
    str(project_root / 'src' / 'main' / 'python' / 'fman' / 'main.py'),
    '--name', 'fmanYS-portable',
    '--onefile',
    '--windowed',
    '--noupx',
    '--icon', str(project_root / 'src' / 'main' / 'icons' / 'Icon.ico'),
    '--add-data', f"{target_fmanys / 'constants.json'}{sep}.",
    '--add-data', f"{target_fmanys / 'Plugins'}{sep}Plugins",
    '--add-data', f"{target_fmanys / 'styles.qss'}{sep}.",
    '--add-data', f"{target_fmanys / 'os_styles.qss'}{sep}.",
    '--add-data', f"{target_fmanys / 'Icon.ico'}{sep}.",
    '--collect-data', 'certifi',
    '--hidden-import', 'requests',
    '--hidden-import', 'ctypes.wintypes',
    '--hidden-import', 'adodbapi',
    '--hidden-import', 'win32com.shell.shell',
    '--hidden-import', 'win32com.shell.shellcon',
    '--hidden-import', 'win32gui',
    '--hidden-import', 'winpty',
    '--hidden-import', 'win32wnet',
    '--hidden-import', 'tinycss',
    '--hidden-import', 'tinycss.parsing',
    '--additional-hooks-dir', str(fbs_hooks_dir),
    '--runtime-hook', str(fbs_hook),
    '--runtime-hook', str(portable_hook),
    '--distpath', str(pyinstaller_dir / 'fmanYS-portable'),
    '--workpath', str(pyinstaller_dir / 'build'),
    '--specpath', str(pyinstaller_dir),
    '--log-level', 'ERROR',
    '--noconfirm',
]

print(f"Building portable exe (project root: {project_root})...")
PyInstaller.__main__.run(args)
print("Done! Output: target/PyInstaller/fmanYS-portable/fmanYS-portable.exe")
